### ISSUE TITLE
update flux

### ISSUE THREAD

**Issue by daisyanne1380** [rathena/FluxCP#111]
So i notice if you have a external database you can install flux fine with no issue as a clean install. BUT if you update flux and run the update it will ignore the server connections that say the database is external and default to Localhost. When i deleted all my CP tables and went with a clean install it worked again.  So there is something wrong with update script where it doesnt look at the server ip and determine its not localhost. 

here is the error on update. ehost is localhost where the CP is running on
Message: SQLSTATE[28000] [1045] Access denied for user 'ragna'@'e43.ehosts.com' (using password: YES)

 this is my setting in server.php
				// -- It specifies the encoding to convert your MySQL data to on the website (most likely needs to be utf8)
			'Hostname'   => '66.85.75.66',
			'Username'   => 'ragna',
			'Password'   => 'blankout',
			'Database'   => 'ragna',

On clean install the installer works great no issue. This only happens when you try to update. When you try to update it also ask for mysql username and password But it does not ask for ip of the server so its already assuming localhost. as shown below

Alternative MySQL username/password
MySQL username	
MySQL password

if you try to use the update all option you get a duplicate column error.

**Comment by Akkarinage** [comment]
The update script executes the new scripts on the files in the database on the host specified in servers.php. The Update All option has worked fine for a long time, it'd be interesting to see the actual error you get. A "duplicate column error" could mean anything.


It's been a very long time since i've used the manual sql credential method to update anything, i'll see if there's anything that can be done to make it more efficient.

**Comment by daisyanne1380** [comment]
hi this is the entire error:

Critical Error

An error was encountered during the lifetime of the application.

This could be due to a variety of problems, such as a bug in the application.

However, normally it is caused by misconfiguration.

Exception Details

Error: Flux_Error

Message: Critical MySQL error in Installer/Updater: Duplicate column name 'use_existing'

File: /home2/daydrea2/public_html/main/lib/Flux/Installer/Schema.php:131

File	Line	Function/Method
/home2/daydrea2/public_html/main/lib/Flux/Installer/Schema.php	155	Flux_Installer_Schema::install()
/home2/daydrea2/public_html/main/lib/Flux/Installer.php	75	Flux_Installer_Schema::update()
/home2/daydrea2/public_html/main/modules/install/index.php	31	Flux_Installer::updateAll()
/home2/daydrea2/public_html/main/lib/Flux/Template.php	375	include()
/home2/daydrea2/public_html/main/lib/Flux/Dispatcher.php	170	Flux_Template::render()
/home2/daydrea2/public_html/main/index.php	177	Flux_Dispatcher::dispatch()
Exception Trace As String

#0 /home2/daydrea2/public_html/main/lib/Flux/Installer/Schema.php(155): Flux_Installer_Schema->install(20081109093448)
#1 /home2/daydrea2/public_html/main/lib/Flux/Installer.php(75): Flux_Installer_Schema->update()
#2 /home2/daydrea2/public_html/main/modules/install/index.php(31): Flux_Installer->updateAll()
#3 /home2/daydrea2/public_html/main/lib/Flux/Template.php(375): include('/home2/daydrea2...')
#4 /home2/daydrea2/public_html/main/lib/Flux/Dispatcher.php(170): Flux_Template->render()
#5 /home2/daydrea2/public_html/main/index.php(177): Flux_Dispatcher->dispatch(Array)
#6 {main}

**Comment by Akkarinage** [comment]
The updater shouldn't re-process updates that have already been ran.. so this is odd.

**Comment by daisyanne1380** [comment]
the only way i can install flux is by deleting the old flux database and it will install fresh

**Comment by Akkarinage** [comment]
When moving Flux to a different location, the cache needs to be flushed but the schema logs need to be transferred, otherwise flux will try to re-run the sql scripts and that's where you get the SQL errors like the one above. I'll setup a test environment and try different ways of breaking it.

**Comment by daisyanne1380** [comment]
after doing a clean install of a older flux from 2 month ago and clearing cache and cookies i tried to run update and still got
An error was encountered during the lifetime of the application.

This could be due to a variety of problems, such as a bug in the application.

However, normally it is caused by misconfiguration.

Exception Details

Error: Flux_Error

Message: Critical MySQL error in Installer/Updater: Duplicate column name 'use_existing'

File: /home2/daydrea2/public_html/main/lib/Flux/Installer/Schema.php:131

File	Line	Function/Method
/home2/daydrea2/public_html/main/lib/Flux/Installer/Schema.php	155	Flux_Installer_Schema::install()
/home2/daydrea2/public_html/main/lib/Flux/Installer/MainServer.php	52	Flux_Installer_Schema::update()
/home2/daydrea2/public_html/main/modules/install/index.php	83	Flux_Installer_MainServer::updateAll()
/home2/daydrea2/public_html/main/lib/Flux/Template.php	375	include()
/home2/daydrea2/public_html/main/lib/Flux/Dispatcher.php	170	Flux_Template::render()
/home2/daydrea2/public_html/main/index.php	177	Flux_Dispatcher::dispatch()
Exception Trace As String

#0 /home2/daydrea2/public_html/main/lib/Flux/Installer/Schema.php(155): Flux_Installer_Schema->install(20081109093448)
#1 /home2/daydrea2/public_html/main/lib/Flux/Installer/MainServer.php(52): Flux_Installer_Schema->update()
#2 /home2/daydrea2/public_html/main/modules/install/index.php(83): Flux_Installer_MainServer->updateAll()
#3 /home2/daydrea2/public_html/main/lib/Flux/Template.php(375): include('/home2/daydrea2...')
#4 /home2/daydrea2/public_html/main/lib/Flux/Dispatcher.php(170): Flux_Template->render()
#5 /home2/daydrea2/public_html/main/index.php(177): Flux_Dispatcher->dispatch(Array)
#6 {main}

The only way i get this to work is by doing a back up of my cp database then clean install then i restore data.

**Comment by jturolla** [comment]
This seems to be broken.

**Comment by cydh** [comment]
this error `use_existing` in my case, it's halted in cp_itemshop same as https://rathena.org/board/topic/113129-error-instalation-use_existing/#comment-335376

1. Use the used database with old flux cp_ tables
2. at first, everythingin version_installed marked as red none
3. just try install anyway
4. then that use_existing error pops out
5. back to install page, the result as this image below
![image](https://user-images.githubusercontent.com/4016864/41753400-66ec226a-75f7-11e8-9110-8a3adee8d030.png)

**Comment by cydh** [comment]
the good cause that crossed in my mind is
it's detected as `20080928225124`
```sql
CREATE TABLE IF NOT EXISTS `cp_itemshop` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `nameid` int(11) unsigned NOT NULL default '0',
  `quantity` int(11) unsigned NOT NULL default '0',
  `cost` int(11) unsigned NOT NULL,
  `info` text,
  `create_date` datetime NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM COMMENT='Item shop';
```
which in 2009 there's
```sql
ALTER TABLE `cp_itemshop` ADD `category` INT(11) NULL AFTER `nameid`;
```

in fact, the current table has `category` field already
![image](https://user-images.githubusercontent.com/4016864/41753689-21bb0358-75f9-11e8-8814-6cfacd0b2b6d.png)

**Comment by cydh** [comment]
**I guess this is intended** (yet) for a new installation but using old tables. It's because in **your new flux** installation/updates data logs are empty, doesn't have the old logs from your *old flux*.

So then
1. copy tables are not really compatible with installer
2. if still want to do a copy, make sure you also copy the files `/data/logs/schemas/charmapdb/<yourROname>/<yourROCharServerName>`
3. if have no idea what are the files
   1. Check the tables
   2. Check if the columns/stuctures are same in the latest ver inside .sql files in `/data/schemas/charmapdb`
   3. Make an empty file same with the latest (or all) schemas, but save with extension `.txt`
4. Re-run the install

And for yet, better make this issue as invalid but mostly becomes knowledgebase. I said (yet). Maybe later we need to update the schemas remove the old update sqls. Like other Framework maybe, they put "how to migrate from *old version* to this version" xD

**Comment by Akkarinage** [comment]
This basically boils down to the same issue in #168 - I'll close this one and leave the other open as it contains a usable work-around for testing.
