### ISSUE TITLE
admin_spawn

### ISSUE THREAD

**Issue by sader1992** [rathena/FluxCP#135]
Internal server error

This website might have encountered a technical problem and cannot fulfill your request.
Please try again later.

Error code 500 (Internal Server Error)

when trying to upload the npc folder(as zip)

it get uploaded btw but the error stoping the request

**Comment by Akkarinage** [comment]
I might be able to help you if you provide error logs..
I'm not a crystal ball.

**Comment by sader1992** [comment]
i don't know if flux log anything
but those are the logs from my apache
(i did clear the logs first then re try to upload the npc file to get the logs of the problem so this is all the log file)

http://imgur.com/vJlO5Wu    >>> from the browser
http://imgur.com/AHEVGdS    >>> from the server

192.168.1.2 - - [28/Jun/2017:17:53:16 +0200] "GET /flux/?module=admin_spawn HTTP/1.1" 200 3874 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.168.1.2 - - [28/Jun/2017:17:53:16 +0200] "GET /themes/bootstrap/img/load.gif HTTP/1.1" 404 486 "http://192.168.1.210/flux/?module=admin_spawn" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.168.1.2 - - [28/Jun/2017:17:53:17 +0200] "GET /themes/bootstrap/img/load.gif HTTP/1.1" 404 486 "http://192.168.1.210/flux/?module=admin_spawn" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
192.168.1.2 - - [28/Jun/2017:17:53:33 +0200] "POST /flux/?module=admin_spawn HTTP/1.1" 500 295 "http://192.168.1.210/flux/?module=admin_spawn" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

**Comment by Akkarinage** [comment]
That is from your access_log - i need the data from your error_log.

**Comment by sader1992** [comment]
there is no error at all else then when i restart apache i get this only

[Wed Jun 28 20:22:35.664584 2017] [mpm_prefork:notice] [pid 19292] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Jun 28 20:22:35.664672 2017] [core:notice] [pid 19292] AH00094: Command line: '/usr/sbin/apache2'

**Comment by sader1992** [comment]
missclick :x

**Comment by srhmike** [comment]
I havent been able to get the npcs to load either.  Or the item descriptions with lua
