### ISSUE TITLE
Add optional memcache support

### ISSUE THREAD

**Issue by anacondaq** [rathena/FluxCP#142]
### Problem

- server status query (yes, i saw file cache, but it's not so fast as memory one)
- server online
- different ranks
- generating main page / different pages

First of all, before I will start explaining let me bold few important points which are used when opened the issue:

1. FluxCP is `#1` control panel which used mostly on the very big part of websites, this happened not because people love this panel, this happened because this panel is available for free for all and people don't have alternatives. 
2. FluxCP in 90% cases or more used at a Front-End main website with a custom design with many queries. This point important as `1.` point. And it's open a lot of problems to a game database which bounded to fluxcp. Each visitor provokes extra load to game-server and load to PHP on a webserver. Imagine what will happen with DoS? 
3. All modern and popular cms like FluxCP already has caching mechanisms for most critical queries.

### What will be solved with optional Memcache

1. Will be dramatically decreased overall PHP, MySQL (at game-server too), loading. It will open a lot of cases to host the app on a weak server or don't worry about script kiddies with different tools, or for heavy loadings when for example WoE ends or other event ends and everyone rushes to the web-panel to see detailed stats.

2. Will be added configs and different examples in code which can be used by totally newbies for adding to Memcache their own key/values via very simple code edits (for rare cases)

3. All ranks, front-end page, etc pages will be ultra-fast.

4. newbies will know how to increase performance of their front-end website in several times

### How to implement and what need to cache

1. Add to application.conf settings to enable optional Memcache, then inside the block all settings related to Memcache, server, IP, etc minimum info. Add option which can tell people for how long they will store a data in Memcache

2. Review code and add Memcache strings for different heavy PHP operations and MySQL operations

### What it will give?

First of all, Memcache support will decrease loads, and increase in several times performance. All that requested from devs is start a work with implementation and maybe others (me not an exception) will join with different tests, etc and will add their own queries. 

### How about alternatives?

Of course there are opcache, apcu, fastcgi_cache, proxy_cache but they not so effective as Memcache, and so easy to setup. When I talk about the things explained in the issue, I'm thinking about newbies in mind.

**Comment by Akkarinage** [comment]
These are all excellent points.

Memcache isn't newbie friendly in the slightest, as an additional service (Memcached) needs to be running alongside php, as well as having the ability to install the memcache php module. This creates a problem for anyone using shared webhosting.
