### ISSUE TITLE
Markdown lib removal?

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#151]
Off the top of my head, the markdown lib is only used for email formatting and itemshop descriptions, and I'm willing to bet that very few people actually use markdown in that box.

In order to remove a buggy library and keep sensio  happy, I propose it is removed. We can either keep it as a plain textarea or we can apply tinymce to it for easier editing.

Email templates can become normal html without the need for format conversion.

**Comment by aleos89** [comment]
Just remove it. There's no reason to support buggy code unless there's a cleaner, well supported library.

**Comment by hurtsky** [comment]
+1 👍
