### ISSUE TITLE
Email Confirmation (enabled)

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/FluxCP#156]
![double http](https://user-images.githubusercontent.com/4651777/32988358-cee57c08-cd3d-11e7-9003-b1fa41ad6be8.PNG)

giving invalid activation link? please refer to the attached picture thanks.

**Comment by ernestfegarido** [comment]
erase the other "http" resolve the problem.

**Comment by ernestfegarido** [comment]
@aleos89 check this out

**Comment by aleos89** [comment]
Probably an issue with your config. Check [here](https://github.com/rathena/FluxCP/blob/master/config/application.php#L5) and make sure your config follows what the comment states.
