### ISSUE TITLE
Credits not Added after Donation

### ISSUE THREAD

**Issue by ecdarreola** [rathena/FluxCP#157]
Hi,

I tried to enable donation on Flux, but after someone donated on the server the credits wasn't added on the account.

Also there was no logs on CP Logs that there was a transaction in the Paypal. I received the amount though.

What seems to be the problem on it?

Regards!

**Comment by ecdarreola** [comment]
In the paypal logs in flux,

It says:
[2017-11-15 01:22:34] Receiver e-mail (XXXX@hotmail.ph) is not recognized, unauthorized to continue.

How to fix this? How to make email recognized?

**Comment by aleos89** [comment]
It's an issue on your end with possibly having multiple logins for your PayPal:
```
	'PayPalReceiverEmails' => array(                    // These are the receiver e-mail addresses who are allowed to receive payment.
		//'admin2@localhost',                             // -- This array may be empty if you only use one e-mail
		//'admin3@localhost'                              // -- because your Business Email is also checked.
	),
```

**Comment by ecdarreola** [comment]
@aleos89 : Should I add all logins?

**Comment by aleos89** [comment]
List all logins except for the login you entered in `PayPalBusinessEmail`.
