### ISSUE TITLE
FluxCP doesn't keep session data across multiple webservers

### ISSUE THREAD

**Issue by ghTravis** [rathena/FluxCP#165]
Hi,

Today I attempted to setup FluxCP across multiple web servers behind a load balancer. After logging in, I wasn't able to keep myself logged in when refreshing and landing on a different server.

Might be worth looking into storing session data in the browser or database in order to keep a user logged in.

Thanks.
Travis

**Comment by Akkarinage** [comment]
Well.. obviously not. The user session is stored within the generic php session module, and i'm against storing anything in the browser. Unless you have a ridiculous number of concurrent connections, there is no reason to use load balancing. FluxCP also stores logs per installation, so if errors are created you'd need to check each webserver until you find the relevant files.

This is not an issue, this is a denied feature request.
