### ISSUE TITLE
Extra comma before commented line

### ISSUE THREAD

**Issue by gladio78** [rathena/FluxCP#179]
https://github.com/rathena/FluxCP/blob/247735f57ba6526fa56e97957948e57aa8f32ade/config/servers.php#L50

Hi 
the array declaration should terminate without a comma, it is clearly involuntary caused by the comment of the last element

**Comment by cydh** [comment]
nothing wrong it that. trailing comma in multi-line array definition is valid, it's easier to add new element later which is not disturb diff

[Array](http://php.net/manual/en/function.array.php)
> Having a trailing comma after the last defined array entry, while unusual, is a valid syntax.
