### ISSUE TITLE
Can't change Group ID for any player using ADMIN acount

### ISSUE THREAD

**Issue by hendra814** [rathena/FluxCP#207]
here list my account
![image](https://user-images.githubusercontent.com/9587609/42984255-dc3db6bc-8c15-11e8-86e9-a75dd7178eef.png)

and i wnat change 2000002 acoount into group ID 0
![image](https://user-images.githubusercontent.com/9587609/42984266-f04eb322-8c15-11e8-9d86-490ad9cd5701.png)

![image](https://user-images.githubusercontent.com/9587609/42984275-f7ddff44-8c15-11e8-8b96-1658bf2b629b.png)

the result still group ID 99
![image](https://user-images.githubusercontent.com/9587609/42984282-05d0daae-8c16-11e8-8fc2-c6357ce87dd6.png)

but work for change credit ammount.
![image](https://user-images.githubusercontent.com/9587609/42984308-1b82cb78-8c16-11e8-9197-71aea2a9259b.png)

Please Help.
Thanks before.

**Comment by cydh** [comment]
update your fluxcp files. everything works on me

**Comment by hendra814** [comment]
@cydh 
already
![image](https://user-images.githubusercontent.com/9587609/42992494-e77d0ac4-8c32-11e8-8638-dd335f02fa86.png)

**Comment by hurtsky** [comment]
its working @hendra814 , just test this..

**Comment by hendra814** [comment]
@hurtsky 
could you share your modules/account/edit.php and modules/account/view.php

sorry i don't know this part git status path/to/modules/account/edit.php but i already check.
it's same with in the git (master branch)

**Comment by hurtsky** [comment]
it is same with the current git, @hendra814 try check any Apache/php error.. we can continue this in discord

**Comment by cydh** [comment]
mine from this github

**Comment by hendra814** [comment]
@cydh 
today i'm update my xampp into 5.6.36
and then get this error on error log when try modify Group ID

> [Tue Jul 31 13:11:23.637928 2018] [:error] [pid 23104:tid 1960] [client ::1:51511] PHP Notice:  Undefined variable: vip_time in C:\\xampp\\htdocs\\Rathena\\modules\\account\\edit.php on line 74, referer: http://localhost/Rathena/?module=account&action=edit&id=2000002

**Comment by cydh** [comment]
Thank you #209
I'll merge it later

**Comment by hendra814** [comment]
@cydh 
OK, i already update by manual and it's work now for change group ID
