### ISSUE TITLE
MVP Rank error

### ISSUE THREAD

**Issue by xHelenax** [rathena/FluxCP#215]
Not sure if this has been reported yet, but when I go to **?module=ranking&action=mvp**
it gives a missing table error (with de-bug mode activated):

Exception Details
Error: Flux_Error

Message: MySQL error (SQLSTATE: 42S02, ERROR: 1146): Table 'ragnarok.monsters' doesn't exist

File: /home/xxxx/public_html/lib/Flux/Connection/Statement.php:27
______________________________________________________________________________

ragnarok.monsters isn't a table that should actually exist, is it? I thought maybe I did something wrong so I decided to check out other CPs and they return the same error message, like this demo site: 
**https://hurtsky.com/FluxCP/?module=ranking&action=mvp**

Thanks for your consideration of fixing this in advance. :)

**Comment by cydh** [comment]
confirmed if the log tables and mob tables are in different database
