### ISSUE TITLE
Registration error "Uh oh, what happened?"

### ISSUE THREAD

**Issue by cydh** [rathena/FluxCP#221]
If FluxCP cannot register a new player because of the mysql user does not have permission to insert new data, it will return `false` in `LoginServer::register`, the message will be
```
Uh oh, what happened?
```
Should be changed with decent error message

**Comment by Daegaladh** [comment]
Better check for mysql permissions when installing

**Comment by Akkarinage** [comment]
When removing the INSERT privilege from the MySQL user, the Critical Error page is displayed with the following information:
```
Exception Details
Error: PDOException

Message: SQLSTATE[42000]: Syntax error or access violation: 1142 INSERT command denied to user 'ragnarok'@'localhost' for table 'login'

File: C:\xampp\htdocs\FluxCP\lib\Flux\Connection\Statement.php:50
```
