### ISSUE TITLE
Custom field - Paypal

### ISSUE THREAD

**Issue by LunarSHINING** [rathena/FluxCP#239]
The custom field is created in the button, but the payment returns without anything in the custom field ergo failing to locate server or account id and not automatically giving the CP.

**Comment by Akkarinage** [comment]
It is indeed automatically filled in via the button code in https://github.com/rathena/FluxCP/blob/master/data/paypal/button.php

The data is serialized and then broken down again once payment is complete. If you're not getting back, check your Paypal transactions via their site and then cross-reference with your Paypal logs on your webserver. If there's no correlation, then the transaction didn't originate from within your FluxCP installation.
