### ISSUE TITLE
Item page error

### ISSUE THREAD

**Issue by Sephiroth91** [rathena/FluxCP#241]
Hello dears,
I get the following error:

[2019-05-31 20:50:11] [SQLSTATE=42000] Err 1055: Expression #12 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'rathena.cp_itemshop.cost' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

I have read that this error is common in mysql 5.7. Everything else works but I need mysql 5.7 for other projects, so I can't change the version. Is the problem solvable? Can anyone help me? Since it appears to be a general problem, a fluxcp update for mysql 5.7 might make sense.

**Comment by S-anasol** [comment]
You can disable strict mode in your mysql server: https://gist.github.com/nfourtythree/90fb8ef5eeafdf478f522720314c60bd


Or add here https://github.com/rathena/FluxCP/blob/master/lib/Flux/Connection.php#L96
these 2 lines:
```
$sth = $this->getStatement("set session sql_mode='NO_ENGINE_SUBSTITUTION'
");
$sth->execute();
```

**Comment by Sephiroth91** [comment]
I have choose version 2 and it works well.
Thank you
