### ISSUE TITLE
One of the SQL Queries has compatability issues.

### ISSUE THREAD

**Issue by Skormie** [rathena/FluxCP#247]
Error: Flux_Error

Message: MySQL error (SQLSTATE: 42000, ERROR: 1055): Expression #12 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ragnarok.cp_itemshop.cost' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

File: flux_cp/modules/item/index.php:283

**Comment by sanasol** [comment]
Also some workarounds:
https://github.com/rathena/FluxCP/issues/241#issuecomment-497885070

> To:
$sql = $paginator->getSQL("SELECT $col FROM $tableName $sqlpartial GROUP BY items.id, $shopTable.id");

not sure how that could help you while error about `cost` column?
