### ISSUE TITLE
Webhook Discord not Working!

### ISSUE THREAD

**Issue by RagnaWay** [rathena/FluxCP#254]
In the past, it worked perfectly, but I noticed that it stopped working. I use this function (DiscordSendOnNewTicket) in the "servicedesk" module

**Comment by plsfixrito** [comment]
I got the same problem. I don't know what changed (it's probably on discord side), but after changing json_encode to http_build_query in discordwebhook.php it started working again.

**Comment by RagnaWay** [comment]
@plsfixrito Working! thanks.
