### ISSUE TITLE
Donation not credited to account

### ISSUE THREAD

**Issue by ecdarreola** [rathena/FluxCP#260]
I'm using latest revision of fluxcp and followed the instruction completely in config/application.php.
Unfortunately, credits are not automatically added to a donor account.
What could be the possible source?

Useful Info:
- IPN used: both www.paypal.com / ipnpb.paypal.com
- paypal.log.php isn't created even if the logs folder has 0755 permission recursively.
- CP Logs - paypal transaction doesn't reflect.
- login server and char/map server has different DB.

Am I missing something?

**Comment by sanasol** [comment]
You can try configure IPN here
https://www.paypal.com/cgi-bin/webscr?cmd=_profile-ipn-notify

with
`https://you-domain.com/?module=donate&action=notify`

**Comment by ecdarreola** [comment]
@sanasol Done configuring and went to IPN history page to resend the msg but I haven't received it on my end.

paypal.log.php is still not present.

**Comment by sanasol** [comment]
So thats not paypal or flux problem probably.
I mean domain unreachable from Paypal's end for some reason.
Domain it registered more that 2 days?
Maybe http/https error, not sure but it may require httpS for new sites.
Or in the end nginx/apaches problem, check access.log/error.log for your site, maybe paypal tried to access `?module=donate&action=notify` but got some error.

**Comment by ecdarreola** [comment]
Will look at it. Seems weird cause before same config has been used and it's working fine.

The website is months old and reachable.

**Comment by sanasol** [comment]
https://github.com/rathena/FluxCP/blob/master/config/access.php#L14

Fixed, someone set wrong access config for donate/notify page.

Default and correct ANYONE.
