### ISSUE TITLE
How to change encoding

### ISSUE THREAD

**Issue by juliofortunato** [rathena/FluxCP#261]
My FluxCP is showing an unknown character on words with accents.
How can I change the encoding so the panel can deal with accents?

## Preview

![image](https://user-images.githubusercontent.com/4470902/80625930-3fad5000-8a24-11ea-99f6-ff6128b53ca4.png)

Thanks!

**Comment by RagnaWay** [comment]
enable **'Encoding'   => 'utf8',**
https://github.com/rathena/FluxCP/blob/master/config/servers.php#L12

**Comment by juliofortunato** [comment]
@RagnaWay Thanks!
