### ISSUE TITLE
MVPs Ranking not working on the latest version.

### ISSUE THREAD

**Issue by bgamez23** [rathena/FluxCP#263]
![image](https://user-images.githubusercontent.com/1854368/81267833-ad3b2b00-9079-11ea-9346-1ec0892c3759.png)

**Comment by sanasol** [comment]
Probably fixed in https://github.com/rathena/FluxCP/commit/5007e776bd4f345efff93f627dbe595c0ee945b6

Not sure, can't repeat error on my environment.

**Comment by bgamez23** [comment]
thanks it works now after updating
