### ISSUE TITLE
Vote for points bug

### ISSUE THREAD

**Issue by Aerstme** [rathena/FluxCP#265]
The system works fine the first time, but after the countdown ends for voting again it doesn't add the point and redirects you to Flux instead of the voting page. This happens to all the players on my server. I tried doing a clean install but still get the same result.

I have all the default values in `addons / voteforpoints / config / addon.php, except 'PointsType' => "vote",`

https://www.youtube.com/watch?v=eAeSuRCoQFI

**Comment by shatowolf** [comment]
i can confirm this... if you clear your cp_vfp_logs  it will work. and after 12 hours not working again.

**Comment by HiwaRO** [comment]
Bump, was there any long-term fix on this? It does the same to me, it's kind of inconvenient to have to clear the cp_vfp_logs every time.

**Comment by Akkarinage** [comment]
FluxCP doesn't come with a Vote4Points addon, so I'm closing this.

**Comment by sanasol** [comment]
https://github.com/sanasol/FluxCP_Addons-VoteForPoints
fixed some bugs
1. unable to vote more than one time
2. incorrect cashpoints balance display
3. upload voting site image via add/edit form
