### ISSUE TITLE
Guild Emblem After Webservice

### ISSUE THREAD

**Issue by admkakaroto** [rathena/FluxCP#266]
Well, I don't need to describe much, just that after the update of the new client that uses the webservice to store the guild emblem, fluxcp stopped having the guilds emblem working.

**Comment by baggerest** [comment]
The guild icon has been changed in the game. If you look at the webpage, the icon will not be changed, but the order will be changed.

**Comment by Balferian** [comment]
@baggerest is this a browser cache problem?
Do you try reload page with cache?

**Comment by Akkarinage** [comment]
Closed in #278
