### ISSUE TITLE
[ question ] Is the Discord link in readme file dead?

### ISSUE THREAD

**Issue by farishan** [rathena/FluxCP#290]
![image](https://user-images.githubusercontent.com/25826312/122966577-af626500-d3b3-11eb-9c07-0da16a689c9b.png)

Is it just me (because of IP ban), or the link is just not working anymore? Anybody want to update/remove it?

**Comment by gercamjr** [comment]
It's not just you. I get the same "Invite invalid" message.

**Comment by sanasol** [comment]
https://discord.gg/kMeMXWEvSV

Fixed https://github.com/rathena/FluxCP/commit/cfc9d1d919404fb50edcb11a3f533614c0e7af2a
