### ISSUE TITLE
Card 0 - 3 should be named Slot 1 - 4

### ISSUE THREAD

**Issue by Everade** [rathena/FluxCP#293]
Updating the ancient (Card 0 - Card 3) with (Slot 1 - 4) would be great.
Because first and foremost, gear slots are not card exclusive, and secondly, the 0-3 doesn't make sense from a player perspective either.

Would be great if that could be updated on all tables
Speaking about the visual perspective for end-users.
![image](https://user-images.githubusercontent.com/12261601/126208523-ee71cff7-eb2f-448b-a225-606ffb8d9095.png)

**Comment by gamingmagic** [comment]
FluxCP / themes / default / character / view.php

look for this line

<h3>Inventory Items of <?php echo htmlspecialchars($char->char_name) ?></h3>
<?php if ($items): ?>
	<p><?php echo htmlspecialchars($char->char_name) ?> has <?php echo count($items) ?> inventory item(s).</p>
	<table class="vertical-table">
		<tr>
			<th>Item ID</th>
			<th colspan="2">Name</th>
			<th>Amount</th>
			<th>Identified</th>
			<th>Broken</th>
			<th>Card0</th>
			<th>Card1</th>
			<th>Card2</th>
			<th>Card3</th>
			<th>Extra</th>
