### ISSUE TITLE
Critical Error Message: Failed to import/replace rows from table 'db.item_db2'

### ISSUE THREAD

**Issue by xponzy** [rathena/FluxCP#295]
![Screenshot_9](https://user-images.githubusercontent.com/94275985/147492509-36947b5e-17ca-45c7-a3c7-6887143c1985.png)

**Comment by Balferian** [comment]
@xponzy try this fix from @Lemongrass3110.
https://github.com/rathena/FluxCP/pull/275/commits/36984ab5d9bb794e0ae2ed096effe66fa59339b8

**Comment by xponzy** [comment]
> @xponzy try this fix from @Lemongrass3110. [36984ab](https://github.com/rathena/FluxCP/commit/36984ab5d9bb794e0ae2ed096effe66fa59339b8)

Thanks you :)

**Comment by Lemongrass3110** [comment]
Fixed in d83a7f6
