### ISSUE TITLE
Error on view item, character, mob

### ISSUE THREAD

**Issue by mazvi** [rathena/FluxCP#296]
**VIEW ITEM:**
Message: MySQL error (SQLSTATE: 21S01, ERROR: 1136): Column count doesn't match value count at row 1
File: lib/Flux/Connection/Statement.php:59

**VIEW CHARACTER:**
Message: MySQL error (SQLSTATE: 42S22, ERROR: 1054): Unknown column 'pet_mob2.name_english' in 'field list'
File: lib/Flux/Connection/Statement.php:59

**MOB INDEX:**
Message: MySQL error (SQLSTATE: 21S01, ERROR: 1136): Column count doesn't match value count at row 1
File: modules/monster/index.php:169

How to reproduce:

Using latest rathena and latest Fluxcp

**Comment by sanasol** [comment]
Do you use latest (rathena newer than ~11 months at least) with new mob_db2?
This field should be available: https://github.com/rathena/rathena/blob/master/sql-files/mob_db2.sql#L9

**Comment by mazvi** [comment]
Okay i will test again this week sorry

**Comment by mazvi** [comment]
solved by @Balferian 

i forgot to import mob_db2 and mob_db2_re because this is zero data so i not imported it :D but this is important to import this sql :D
