### ISSUE TITLE
ITEM TYPE SOME BUG

### ISSUE THREAD

**Issue by AthenaStudioInc** [rathena/FluxCP#297]
Config : Enable Debug
Item Database : Search Item 2234 [ Tiara ] or 2235 [ Crown ]
[ 2234 ] Item name : Not Show
[ 2234 ] Item ID : 2234
[ 2234  ] Item Type : Notice: Undefined index: in /home/dbroprod/domains/db.ro-prontera.com/public_html/lib/Flux.php on line 667

[ 2235 ] Item name : Not Show
[ 2234 ] Item ID : 2235
[ 2234  ] Item Type : Notice: Undefined index: in /home/dbroprod/domains/db.ro-prontera.com/public_html/lib/Flux.php on line 667

Monster Database : 
Osiris : Not Show Item 2235 [ Crown ] in monster drop
Maya : Not Show Item 2234 [ Tiara ] in monster drop

**Comment by AthenaStudioInc** [comment]
![01](https://user-images.githubusercontent.com/40000876/150433848-ec9e59ff-9f5d-4587-a023-4f31645e2e94.png)
![02](https://user-images.githubusercontent.com/40000876/150433850-00e7e1cc-3468-448e-a234-5a4782fa0bb7.png)
![03](https://user-images.githubusercontent.com/40000876/150433851-8aa955cc-ca08-4f1d-879f-88dd3f48d872.png)

**Comment by Balferian** [comment]
Looks like this problem appear for all items from item_db2 table.
Need to check temporary table functions.
https://github.com/rathena/rathena/blob/master/sql-files/item_db2_re.sql#L191

**Comment by AthenaStudioInc** [comment]
> Looks like this problem appear for all items from item_db2 table. Need to check temporary table functions. https://github.com/rathena/rathena/blob/master/sql-files/item_db2_re.sql#L191

that is the problem from item_db2 / item_db2_re too

thank you so much Balferian : )
