### ISSUE TITLE
PHP 8.x compatibility

### ISSUE THREAD

**Issue by Everade** [rathena/FluxCP#299]
Many major hosting platforms do no longer offer PHP 7.2 and below, since PHP are officialy only supported for 2 years upon release.
PHP 7.3 just reached End of Life this year.

We should look forward and start getting FluxCP and used libraries PHP 8.1 compatible.

**Comment by Pokye** [comment]
Really need some fixes to use in php 8, I tested it with my xampp php 8
![image](https://user-images.githubusercontent.com/98105181/153671632-eb83c522-070c-4f4f-8b64-458d074d8c41.png)

**Comment by Akkarinage** [comment]
This was previously fixed in #302
