### ISSUE TITLE
The API key you have entered is invalid. Please review your API key.

### ISSUE THREAD

**Issue by bgamez23** [rathena/FluxCP#305]
![image](https://user-images.githubusercontent.com/1854368/154830043-3a9f3553-a42c-4bd4-87d3-58258d8fac6a.png)

**Comment by vstumpf** [comment]
You need to create and set an API key here: 
https://github.com/rathena/FluxCP/blob/d22f4a27346cc00396b801f63c4a33c4f21faa35/config/application.php#L229

**Comment by bgamez23** [comment]
> TinyMCEKey

oh okay thanks.
