### ISSUE TITLE
Issue on Character List in Account and Admin Menu

### ISSUE THREAD

**Issue by lelouch22** [rathena/FluxCP#307]
The character list on accounts and admin menu didn't show up even though there are already characters in the sql, it only says "No characters found." or "This account has no characters on FluxRO.". I'm currently using the latest commit 6d95229.

**Comment by reunite-ro** [comment]
> The character list on accounts and admin menu didn't show up even though there are already characters in the sql, it only says "No characters found." or "This account has no characters on FluxRO.". I'm currently using the latest commit [6d95229](https://github.com/rathena/FluxCP/commit/6d95229ed91b40d3d74fe52bc3224725ef9abff0).

are you using the latest rathena git ?

Older rathena git which still using TXT might still have issue since latest fluxcp are using YML.

Make sure use default theme not your own custom theme.

**Comment by Balferian** [comment]
> The character list on accounts and admin menu didn't show up even though there are already characters in the sql, it only says "No characters found." or "This account has no characters on FluxRO.". I'm currently using the latest commit [6d95229](https://github.com/rathena/FluxCP/commit/6d95229ed91b40d3d74fe52bc3224725ef9abff0).

You need to use webservice from vstumpf https://github.com/rathena/rathena/pull/5731
or switch off this config https://github.com/rathena/FluxCP/blob/master/config/application.php#L24

**Comment by lelouch22** [comment]
Thanks for the info @Balferian.
