### ISSUE TITLE
OutputCleanHTML & TinyMCE

### ISSUE THREAD

**Issue by renz-dev** [rathena/FluxCP#308]
Assigning  OutputCleanHTML => true
&
enabling TinyMCE by filling 'TinyMCEKey'

Doesn't allow TinyMCE to work on edit pages. It outputs a 'an unexpected token <' in dev console. But if you turn off OutputCleanHTML then TinyMCE works as it should.

**Comment by Akkarinage** [comment]
Do you have Tidy installed?

**Comment by Akkarinage** [comment]
I'll take that as a "no".
