### ISSUE TITLE
Create config to display #CASHPOINTS & #KAFRAPOINTS instead of FluxCP Account Credit

### ISSUE THREAD

**Issue by mazvi** [rathena/FluxCP#310]
Show ROCASH and KAFRACASH on account

**Comment by sanasol** [comment]
https://github.com/rathena/FluxCP/commit/cfd294c751b119f1c90dac1bab4efe723c88a6bf
(older version with **global_reg_value** tables also available https://github.com/sanasol/sanasol/blob/master/paid_addons/fluxcp_credits_to_cashpoints/secret.patch)
Replacement for flux credits to #CASHPOINTS

Should be still actual probably. But not sure about herc/rathena variables database now.

**Comment by mazvi** [comment]
Yes `#CASHPOINT` And `#KAFRAPOINTS`
