### ISSUE TITLE
Show / Hide Zeny from Ranking not working

### ISSUE THREAD

**Issue by xZee0523** [rathena/FluxCP#311]
Show / Hide Zeny from Ranking not working.. I couldn't identify which part of the code is broken however.

**Comment by AraanBranco** [comment]
@xZee0523  Change perms to ADMIN in [Access.php](https://github.com/rathena/FluxCP/blob/master/config/access.php#L90)
```
'zeny'			=> AccountLevel::ANYONE
```
to
```
'zeny'			=> AccountLevel::ADMIN
```
