### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Anjuts** [rathena/FluxCP#314]
This just sudden show today

`Fatal error: Uncaught TypeError: Argument 1 passed to Flux::parseConfig() must be of the type array, integer given, called in /home/html/public_html/lib/Flux.php on line 272 and defined in /home/html/public_html/lib/Flux.php:245 Stack trace: #0 /home/html/public_html/lib/Flux.php(272): Flux::parseConfig(1) #1 /home/html/public_html/lib/Flux.php(961): Flux::parseConfigFile('lang/error_log') #2 /home/html/public_html/lib/Flux.php(478): Flux::getAvailableLanguages() #3 /home/html/public_html/lib/Flux.php(124): Flux::parseLanguageConfigFile() #4 /home/html/public_html/index.php(63): Flux::initialize(Array) #5 {main} thrown in /home/html/public_html/lib/Flux.php on line 245`

Anyone please help on how to fix this? Thanks

**Comment by sanasol** [comment]
It is trying to load language named `error_log` 😃 

You probably have php error_log file in `lang` folder, it should not be there, try delete it.
