### ISSUE TITLE
Need Update to support rA Initial support for web service

### ISSUE THREAD

**Issue by mazvi** [rathena/FluxCP#315]
Need Update to support this https://github.com/rathena/rathena/commit/0ac52d0bb49e858f7ff7774685bb0d18af6d1cf7

because on fluxcp now version the icon not show

**Comment by sanasol** [comment]
https://github.com/rathena/FluxCP/pull/278/files

https://github.com/rathena/FluxCP/blob/master/config/application.php#L24

Is there any changes? Looks same for me.

**Comment by mazvi** [comment]
yes i was set it to true but not work

**Comment by mplaten** [comment]
And Flux webservice don't works if you put webservice in other database.

**Comment by mazvi** [comment]
yes my webservice database is diferrent from main database (like log database different from main), 

how to make it work?

i also have using view mode webservice on my main database bit also not work.

**Comment by mazvi** [comment]
I think fluxcp needs support so that the webservice database can be separate database from main database as well as the log database
