### ISSUE TITLE
<br /><b>Deprecated</b> on registration/login and missing Captcha Bug Report | login button not working

### ISSUE THREAD

**Issue by bgamez23** [rathena/FluxCP#329]
### Environment

```Markdown
- PHP: 8.1.10
- MySQL: 5.7.38
```

### Current Behavior

<br /><b>Deprecated</b> on registration and missing Captcha 

### Steps To Reproduce

newly reinstalled fluxcp. then check the registration.
and also im not able to login in fluxcp. but i can login in game.

### Anything else?

![image](https://user-images.githubusercontent.com/1854368/191641704-e4d4cb93-d452-4363-a0f3-744697323b73.png)

**Comment by Akkarinage** [comment]
For the captcha, it works if you put your keys into config.php. Maybe we should disable captcha by default? 

I don't have PHP 8.1 installed yet (my multiple dev envs are all configured for 8.0), could you dig into your log files and update the Issue with exactly which function has been deprecated?

**Comment by bgamez23** [comment]
> For the captcha, it works if you put your keys into config.php. Maybe we should disable captcha by default?
> 
> I don't have PHP 8.1 installed yet (my multiple dev envs are all configured for 8.0), could you dig into your log files and update the Issue with exactly which function has been deprecated?

i think it should be off by default since you need to input your own keys to the config. since not all captcha will be the same code.

i think the problem is the <br /><b>Deprecated</b>:  
htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in 

the affected line is.
value="<?php echo htmlspecialchars($params->get('username')) ?>" and 
value="<?php echo htmlspecialchars($params->get('email_address')) ?>".

**Comment by AraanBranco** [comment]
> > For the captcha, it works if you put your keys into config.php. Maybe we should disable captcha by default?
> > I don't have PHP 8.1 installed yet (my multiple dev envs are all configured for 8.0), could you dig into your log files and update the Issue with exactly which function has been deprecated?
> 
> i think it should be off by default since you need to input your own keys to the config. since not all captcha will be the same code.
> 
> i think the problem is the Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in
> 
> the affected line is.
> 
> ```
> value="<?php echo htmlspecialchars($params->get('username')) ?>" and 
> value="<?php echo htmlspecialchars($params->get('email_address')) ?>".
> ```

According to the PHP documentation there was a change in PHP 8.1.0 and as a stable version has not yet been released, I recommend using 8.0 or to resolve this error change
`<?php echo htmlspecialchars($params->get('username')) ?>` to `<?php echo htmlspecialchars($params->get('username') || '') ?>` it seems to me that the `htmlspecialchars()` function will no longer accept null value
