### ISSUE TITLE
Vote - How do you process donations?

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#332]
### Provide Details

So that I can gauge how you guys use FluxCP, can you please use the following emoji reactions for:

👍 I use the FluxCP Shop and provided Donation NPC. Shop Credits are stored via FluxCP. This is the default setup.

👎 I use the Item Shop on FluxCP but have changed the Shop Credits to use in-game CashPoints instead. Items are delivered via the provided Donations NPC.

🚀  I don't use the Item Shop, I use the in-game CashShop and convert donation Credits into CashPoints.

👀  I wrote my own script to handle it all.

If you're using a different method to handle this process, please reply with a comment so I can evaluate how best to proceed.

**Comment by Balferian** [comment]
On my server I use FluxCP shop with vote points:
(*screenshots translated with google therefore, in places incorrect display of elements)
![image](https://user-images.githubusercontent.com/16213511/193456197-7590d323-2c92-44e4-abba-dd2753876bbb.png)
And make page for buying cashpoints/vip time for credits:
![image](https://user-images.githubusercontent.com/16213511/193456351-e8492051-f4b3-4d3f-b586-edc05df20a78.png)

Another client chose to realize it like this
(I wrote such a module to order for one server)
it allow to buy packs with items/cashpoints/vip time
I changed the payment system, and now there is no need to replenish the account balance, you will give packs after payment in game
![image](https://user-images.githubusercontent.com/16213511/193456044-41e81b06-2072-4bd9-bf9e-13d82f891440.png)

And all this systems use RoDex mail:
![image](https://user-images.githubusercontent.com/16213511/193456539-005bf9c7-a39d-457d-bb9d-3e811786d04c.png)

**Maybe it will give community some new ideas to implement**
