### ISSUE TITLE
Captcha enabled by default

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#333]
### Environment

```Markdown
- PHP: 8
- MySQL: MariaDB10
```

### Current Behavior

FluxCP is designed to work out-of-the-box in testing enrivonments after the initial installation process is complete. Errors are produced regarding missing Captcha due to the setting `UseCaptcha` being set to `true` by default, though the keys are left as `...`.

### Expected Behavior

No errors. Users should have the ability to set this to true if they intend on using Captcha.

### Steps To Reproduce

Install FluxCP and attempt to create an account.

**Comment by AraanBranco** [comment]
Are you thinking of passing UseCaptcha to false?

**Comment by Akkarinage** [comment]
I am indeed.

**Comment by AraanBranco** [comment]
I believe it could be default `false` and if it is `true` and the keys are like `...` a disclaimer appears and the image not show

**Comment by AraanBranco** [comment]
What do you think? @Akkarinage

**Comment by Akkarinage** [comment]
That is what I alluded to - I haven't created a PR myself to allow others a chance at increasing their Hacktoberfest count. 👍

**Comment by AraanBranco** [comment]
I can take =)
put the hacktoberfest tag and I can do it here

**Comment by AraanBranco** [comment]
@Akkarinage Sorry for the delay, but I think that solves it.
