### ISSUE TITLE
Who's Online don't work

### ISSUE THREAD

**Issue by Arima92** [rathena/FluxCP#335]
### Environment

```Markdown
- PHP 8
- MySQL Workbench 8
- Wamp Server 3.2.6 - 64 Bits
- Windows Server 2019
```

### Current Behavior

Hi, i have just installed FluxCP but when I go to the "Who's Online" page I have the error messages
![issue](https://user-images.githubusercontent.com/116966954/198841373-9794151d-2b6d-45fe-b0be-a0fbc6858d2b.PNG)

### Expected Behavior

View Online Players

### Steps To Reproduce

1: Extract the FluxCP ZIP in www
2: Modify in application.php: 'BaseURI' => 'FluxCP-master', and put a password
3: Modify in server.php: Database username and password
4: Type Localhost/FluxCP-master on google chrome and Install Flux
5: Go to "Who's Online"

**Comment by Akkarinage** [comment]
I can't replicate this. If you can provide an update or if anyone else can reproduce this, I'll happily look into it again.
