### ISSUE TITLE
PDOException error - Base table or view not found 

### ISSUE THREAD

**Issue by akatsukichika** [rathena/FluxCP#340]
### Environment

```Markdown
- PHP: 8.1.16
- MySQL: 10.6.12-MariaDB
```

### Current Behavior

Error: PDOException

Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ragnarok.guild_emblems' doesn't exist
File: /var/www/localhost/htdocs/FluxCP/lib/Flux/Connection/Statement.php:50

### Expected Behavior

Pages are loading correctly

### Steps To Reproduce

Everything is working fine, except when I click to 'My account','Castles', "Who's Online". I get the message on the above. Any ideas what am I doing wrong?

**Comment by sanasol** [comment]
Did you import this to your db?

https://github.com/rathena/rathena/blob/master/sql-files/web.sql
