### ISSUE TITLE
Blank Page after Login

### ISSUE THREAD

**Issue by mazvi** [rathena/FluxCP#351]
### Environment

```Markdown
- PHP: PHP Version 5.6.37
- MySQL: 10.2.44-MariaDB
```

### Current Behavior

after update to latest fluxcp if we login to fluxcp we will get blank page at ?module=account&action=login&return_url=

### Steps To Reproduce

Update to latest git

```
git pull
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 96 (delta 38), reused 77 (delta 35), pack-reused 0
Unpacking objects: 100% (96/96), done.
From https://github.com/rathena/FluxCP
   833fa09..4b35631  master     -> origin/master
Updating 833fa09..4b35631
```
Updating 833fa09..4b35631

then try login

after update to latest fluxcp if we login to fluxcp we will get blank page at ?module=account&action=login&return_url=

**Comment by Unarmed88** [comment]
I also experienced this kind of thing, but i solved this. This happen due to application incorrect config especially on host address and setting section. You should not use localhost as default setting on application config

**Comment by mazvi** [comment]
> I also experienced this kind of thing, but i solved this. This happen due to application incorrect config especially on host address and setting section. You should not use localhost as default setting on application config

if on git before it was normal it should be normal now without any changes to the config, besides my serveraddress isn't localhost either iam using the domainname like `panel.domainro.com`

**Comment by secretdataz** [comment]
Blank page usually means PHP errored out before anything can be rendered. Turn on error messages in your PHP settings.

**Comment by mazvi** [comment]
Solved by added / on config application.php `'BaseURI' => '/',`

but this is strange, its must be fine without /

i think the problem come from here 

https://github.com/rathena/FluxCP/commit/9eb87a62bfce6ac068391e90325710c122a79b3b

Find the // Sanitize BaseURI. (leading forward slash is mandatory.)

**Comment by vstumpf** [comment]
Please try #352 for a fix
