### ISSUE TITLE
(PHP-W1000) Array contains duplicate keys

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#356]
## Description
This array contains one or more duplicate keys, which can result in unexpected output. Only the last value associated with the duplicated key will be present in the array.

## Occurrences
There are 60 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/rathena/FluxCP/issue/PHP-W1000/occurrences/](https://app.deepsource.com/gh/rathena/FluxCP/issue/PHP-W1000/occurrences/)

**Comment by AraanBranco** [comment]
Can I get this issue fixed? @Akkarinage
