### ISSUE TITLE
Facebook newsfeed not working

### ISSUE THREAD

**Issue by Freyja-Folkvangr** [rathena/FluxCP#40]
<img width="1266" alt="screen shot 2015-08-18 at 23 20 27" src="https://cloud.githubusercontent.com/assets/6330708/9347429/cc792ca2-45ff-11e5-8867-0373c4d795b3.png">
<img width="1018" alt="screen shot 2015-08-18 at 23 20 34" src="https://cloud.githubusercontent.com/assets/6330708/9347430/cd5fdda0-45ff-11e5-87ee-7949261aea4f.png">

**Comment by Akkarinage** [comment]
There's only 27 lines of code in the original modules/news/index.php file, so you've added code to get an error on line 32, which is just missing a ; if you go by your error.

**Comment by Freyja-Folkvangr** [comment]
I haven't added code..

**Comment by Akkarinage** [comment]
https://github.com/rathena/FluxCP/blob/master/modules/news/index.php then you shouldn't have 32 lines of code, and you shouldn't be getting an error. Paste the contents of your modules/news/index.php
