### ISSUE TITLE
CPU of VPS get max when use FluxCP

### ISSUE THREAD

**Issue by Dark8008** [rathena/FluxCP#48]
![image](https://cloud.githubusercontent.com/assets/14345362/11606319/9341334e-9b4f-11e5-83a1-67e6d2dec064.png)

Please help !

**Comment by Akkarinage** [comment]
I'm not sure I understand what the issue is.. FluxCP looks like it was installed just fine.

If you're referring to your CPU usage; I'm not sure what you would expect anyone to do about that.
