### ISSUE TITLE
Update modules to sync with new sql tables

### ISSUE THREAD

**Issue by TournamentRO** [rathena/FluxCP#53]
have fixed some small issues, but global_reg_value table doesn't exist anymore

my settings are main db and logs are separated

![capture](https://cloud.githubusercontent.com/assets/5636061/12998716/ff5e42a2-d181-11e5-964d-b7c2b57232c2.PNG)

**Comment by TournamentRO** [comment]
since i dont have a repo :)

please implement
in modules/character/view.php

FROM:
$sql .= "LEFT OUTER JOIN {$server->charMapDatabase}.`global_reg_value` AS reg ON reg.char_id = ch.char_id AND reg.str = 'PC_DIE_COUNTER' ";

TO:
$sql .= "LEFT OUTER JOIN {$server->charMapDatabase}.`char_reg_num` AS reg ON reg.char_id = ch.char_id AND reg.key = 'PC_DIE_COUNTER' ";

**Comment by Akkarinage** [comment]
I'm sure there's more than just that one line that would need changing. If there's only a few, though, you can clone the repo and edit directly within github.com, then save changes and submit a pull request without having to clone to your desktop then merge and commit.
