### ISSUE TITLE
Having some issue on template 

### ISSUE THREAD

**Issue by RadianFord** [rathena/FluxCP#54]
`[13-Apr-2016 00:10:39 America/Toronto] PHP Notice:  Undefined offset: 0 in /home/..../public_html/lib/Flux/Template.php on line 1231`

`[13-Apr-2016 00:12:34 America/Toronto] PHP Notice:  Undefined offset: 0 in /home/...../public_html/lib/Flux/Template.php on line 1231`

-- edit --

**Comment by Lemongrass3110** [comment]
Could you please create 2 issues for the different problems?
The one below is because you have the php strict mode enabled and we access a variable in the wrong way.
The other one seems to be different though.
Thank you.

**Comment by RadianFord** [comment]
Yea sure. sorry about that

**Comment by RadianFord** [comment]
Yea sure no problem.

**Comment by Akkarinage** [comment]
Are you using a custom theme or one that is already available with FluxCP?

**Comment by RadianFord** [comment]
@Akkarinage I am using normal fluxCP no theme just the the default style.

**Comment by Akkarinage** [comment]
Duplicate in #69 and fixed in #70
