### ISSUE TITLE
FluxCP addons CMS "Editor" missing

### ISSUE THREAD

**Issue by pr3p** [rathena/FluxCP#56]
Hi sir i've seen that the cms modules was embedded already on fluxcp but as i notice that the cms has missing editor please include the editor in able to used the html base coding, it seems you can only input plain text only unlike the separate addons it has "editor tools" w/c include all tools needed like font,size,color coding,, hyperlink and etc, its included on the files on ( themes\default\tiny_mce) but doesn't work even on default themes. Thanks and looking for your fast response.

**Comment by Akkarinage** [comment]
First mentioned in #49 but no one seems to want to share their fix (if they've fixed it). I'll give those files a poke.
