### ISSUE TITLE
Harmony Logs

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#57]
I'm unsure of how many servers still use Harmony, but I'm willing to bet it's not many. Might be worth removing the Harmony Logs and possibly making them an optional addon module instead.

There's certainly no reason to have the nav link displayed by default.

**Comment by aleos89** [comment]
I'd go with optional since many servers don't even have Harmony to begin with.

**Comment by RagnarokNova** [comment]
Agreed. It's not even supported anymore, most servers still running Harmony are ancient servers that never managed to move on.
