### ISSUE TITLE
Contact Us Module

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#60]
Does anyone even publish the link to this on their sites?

**Comment by aleos89** [comment]
Also seems like another useless feature as most people are contacted through a forum or 3rd party social networking site.

**Comment by RagnarokNova** [comment]
Not only that, but even without taking forum/3rd party social methods into consideration, it'd be so much easier to just put an e-mail address for incoming questions. Most people generally don't like using Contact Us boxes as they very commonly bug out and destroy your messages.

**Comment by Vennren** [comment]
This indeed seems to have lost its use over the years.
Alternative methods to communicate have replaced this as mentioned by Aleos & Nova.

**Comment by KeiroD** [comment]
Eh. Isn't this mostly obsoleted by the Social link on FluxCP? If not, then typically the website owner'll have set up alternate methods. May as well remove this.
