### ISSUE TITLE
TaskList Module

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#62]
Does anyone actually make use of this?

I think it was one of the first fluxcp modules i'd ever written. It sucks and should die in a cyberfire. Unless people are actually using this instead of the many other mediums i.e. forums, facebook group chat, paper and pen, github, etc etc.

**Comment by Mysteries** [comment]
I've never used it in my Flux before. =/

**Comment by aleos89** [comment]
If you end up implementing a forum addon then this feature is useless.

**Comment by RagnarokNova** [comment]
Destroy it.
