### ISSUE TITLE
Preinstallation Checks

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#65]
GD2, mcrypt, etc should be checked before displaying the "insert secret password" page. Most other web software packages have this, there's no reason why we shouldn't either. It'd help to reduce support topics on the forums too.

**Comment by KeiroD** [comment]
Shouldn't be too difficult to display this, especially since it isn't always necessarily obvious that there're additional requirements. (Sendmail, Postfix, etc for the mailer functionality?)

**Comment by Akkarinage** [comment]
![chrome_9Hzl2IW7pD](https://user-images.githubusercontent.com/4101952/194338095-202a2a52-5ece-4698-9159-3a7bbd683631.png)

Tidying up the installation process.
