### ISSUE TITLE
Marketing Module

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#66]
Some servers use their forums to bulk mail, but that doesn't generally give you alot of options for specific groups to send emails to. Other servers upload their login table to automated marketing services to use their entire db to send emails.

Personally, I've used my own version for the last few months and had positive feed back from. Additional options can be added to allow for selecting specific time periods for "You've been gone longer than 6 Months, here's a Jellopy" style emails. A template is thrown into data/templates/ so all you need to do is type a subject, select the template and choose who you're sending to.

This would replace the standard Mail module - #59 

Example:
![ss 2016-06-08 at 07 45 49](https://cloud.githubusercontent.com/assets/4101952/15885154/0d4e38c8-2d4d-11e6-9fa9-4d8adb104e99.png)

**Comment by RagnarokNova** [comment]
Completely for this. Sorting data out of SQL to send e-mails is a chore, and with the info already in Flux, it's a wonder we're not doing more with it. I'm surprised we don't already have a check-box for people to be able to opt-out of a mailing list though.

**Comment by Akkarinage** [comment]
The checkbox is actually a good point..

I can add an opt-out from marketing emails on registration and maybe put a toggle/button/link on the main account page?

**Comment by RagnarokNova** [comment]
Yeah I think that'd be pretty good.
