### ISSUE TITLE
News and Pages CMS

### ISSUE THREAD

**Issue by lelouch22** [rathena/FluxCP#77]
Why there are no Link and Unlink functions?

**Comment by Akkarinage** [comment]
Link and Unlink functions? Example?

**Comment by lelouch22** [comment]
For example in rA post or reply...

Link
![link](https://cloud.githubusercontent.com/assets/4976551/19013100/7d8dce70-87fa-11e6-9dda-befdeb084e6f.jpg)

Unlink
![unlink](https://cloud.githubusercontent.com/assets/4976551/19013104/8105c40e-87fa-11e6-8c1d-510fcc275d68.jpg)

Text with Link
![linkzzz](https://cloud.githubusercontent.com/assets/4976551/19013110/c18b5a3e-87fa-11e6-9224-a88b9e38262a.jpg)

Thats what i am saying becuase [Flux CP CMS Addon 1.2](https://rathena.org/board/files/file/2332-flux-cp-cms-addon/) have this Link and Unlink func on it.

Sorry for this late reply.
