### ISSUE TITLE
CleanURLs non-functional.

### ISSUE THREAD

**Issue by KeiroD** [rathena/FluxCP#84]
Hi,

Note that FluxCP is installed [here](https://ro.lysharia.com). Right now, CleanURLs is not working as I'd hoped. So CleanURLS is disabled at this time.

Quick OS setup:

Ubuntu 16.10 x86_64

```
root@ro:~# apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-18T18:32:02
root@ro:~# php -v
PHP 7.0.12-1+deb.sury.org~yakkety+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1+deb.sury.org~yakkety+1, Copyright (c) 1999-2016, by Zend Technologies
root@ro:~# mysql --version
mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
**EXPECTED BEHAVIOR**
`apache2` is set to use `mod_rewrite`. You can confirm this is the case [here](https://ro.lysharia.com/info.php).

So, `UseCleanUrls` is enabled in `config/application.php` as you'd normally expect.

`.htaccess` has the following:

```
RewriteEngine On
#RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule !\.(js|ico|gif|jpg|png|css|pdf|swf|flv)$ index.php [QSA]
```

Note: the RewriteBase bit here was commented out because I was testing whether or not RewriteBase / would resolve the issue one way or the other. (e.g., whether it'd work with it enabled or not enabled. It did not work either way.)

**RESULT OF ABOVE BEHAVIOR**

Obviously, as you can see, this doesn't work, at least when I enable it. It'll properly create https://ro.lysharia.com/main when CleanURLs are enabled, but as expected, fails to work because it seems that the above rewrite rules fail to work through `index.php`

Any particular suggestions for how one should get CleanURLs working? If I enable it, it breaks.

**Comment by Akkarinage** [comment]
Error logs would be great, as this feature has worked for a number of years and I can't replicate the problem. If no error logs are being produced, use-cases would be great so I can try following along.
