### ISSUE TITLE
Enable MD5, attempt change password, password change fails

### ISSUE THREAD

**Issue by KeiroD** [rathena/FluxCP#85]
You might want to code in a method for users to update their passwords... because I am unable to update my admin account unless I specifically leave `UseMD5` set to `false`.

Of course, to resolve this issue, one could use any MD5 hash generator utilities found online to get around _that_ issue... but still.

**Comment by Akkarinage** [comment]
An error log would be helpful for this issue, as it has always worked before.

Configs are set in [this file](https://github.com/rathena/FluxCP/blob/master/modules/account/changepass.php#L64)

**Comment by KeiroD** [comment]
Unfortunately, no errors were generated other than the "The password you entered is incorrect!" error if you enter your known good passwords.

I was able to reproduce this issue every single time if one does not have hashed passwords and enables `UseMD5 => true,` in `config/servers.php`... and doesn't update their account passwords directly in the database to use MD5 hashes instead of the previously unhashed passwords.

Which is why I mentioned `Of course, to resolve this issue, one could use any MD5 hash generator utilities found online to get around that issue... but still.`

**Comment by Akkarinage** [comment]
Uh.. if you don't have an MD5'd passowrd and have UseMD5 set to true, then ofcourse FluxCP will throw you an error, as it's hashing your entered password and checking the 32 character string against the password in the database.

To use MD5 passwords, UseMD5 must be set to true when registering your account in FluxCP, and your login server must be set to use MD5 passwords too. This isn't a bug, this is user error.

**Comment by KeiroD** [comment]
As I said... if one doesn't set this up from the beginning (poorly worded, unfortunately), and tries to set it up to use MD5 hashes, it will obviously not work as you and I stated.

What I was trying to say is that you _should_ include a method for an admin to convert the unhashed passwords to their hashed counterpart. Which was the entire point of my original post. You saying this is not a bug is incorrect. It's a feature request to make it easier for others to convert it. I resolved this issue myself by using an online MD5 hash generator. Problem solved for me, personally.

But not including it for those who realize that they screwed up in not setting up the MD5 hash or whatever other security method you choose to use to hash passwords makes it harder for them to convert it after-the-fact.

**Comment by Akkarinage** [comment]
rAthena includes this: https://github.com/rathena/rathena/blob/master/sql-files/tools/convert_passwords.sql

It's a bad idea to include further tools for password management other than changing your own password within FluxCP, for security sake.

>  You saying this is not a bug is incorrect.
But.. it's not a bug.

**Comment by KeiroD** [comment]
Huh. I didn't know there was a utility for that right in rAthena. Thanks for pointing that out. Of course, I find out there's an existing option already... _after the fact_. But, it is good to know.

Seriously. It's not a bug. Please reread what I said. I stated that I had poorly worded my statements thus far. It really is not a bug, but a feature request. You asked for error logs. I simply described what happened and noted that I'd solved the issue. Therefore, not a bug. Therefore, a feature request.

I simply wanted to suggest that perhaps one should consider including a utility to make the conversion happen. Again, of course, not realizing that such a thing already exists until you pointed it out.

That said... "It's a bad idea to include further tools for password management other than changing your own password within FluxCP, for security sake."

I'm not sure it's a bad idea. Maybe a note in the wiki somewhere for how to do this would be a thing to do. I didn't even realize that the database passwords were stored in the clear until after I'd set the server up and noticed that the passwords were stored plaintext. Then I went looking for where to convert them to a hashed version.

That led me to the `UseMD5` option in FluxCP. I tried flicking it to `true` and then tried to change my password because I naively assumed that FluxCP would have a method to change the password to a hashed equivalent.

Obviously, this didn't work because FluxCP doesn't have a way for that to happen. Hence the suggestion. And nobody's going to know that it's possible to change the passwords to the hashed version until someone else runs into this issue like I did, and got the suggestion of using `rAthena`'s SQL query to convert the passwords to their hashed versions after-the-fact.
