### ISSUE TITLE
Map/NPC Database Removal?

### ISSUE THREAD

**Issue by Akkarinage** [rathena/FluxCP#92]
The modules are badly written, the author doesn't provide support or fixes and i'm not willing to keep them in this repo if they don't work.

Thoughts?

**Comment by srhmike** [comment]
Id say get rid of them, if they cant be fixed.

**Comment by Akkarinage** [comment]
@FaustVlll

**Comment by daisyanne1380** [comment]
With the last update it works as it should.  Its  a decent module it be nice idea to clean it up rather than scrap it

**Comment by sikiro** [comment]
it provides an alternative option for players and with the monster spawn module it allows server owners to list custom mobs on there that's a neat feature to have.

**Comment by Akkarinage** [comment]
After lot of debugging and countless hours sat staring at this code, i've decided it's best to remove this from the repo. This can still be included as an addon module and is available at https://rathena.org/board/files/file/3393-maps-and-monster-spawns/
