### ISSUE TITLE
Transaction Log

### ISSUE THREAD

**Issue by srhmike** [rathena/FluxCP#96]
After getting a donation, the user that sent the donation cant see anything in Donation History, and when I log in as admin I can't see anything under PayPal Transactions.  But the credit was received.  And paypal shows the donation.

**Comment by itsmeSryx** [comment]
Check or Diff your current `lib/Flux/PaymentNotifyRequest.php` to the latest git.

Also check your `cp_txnlog`

**Comment by Akkarinage** [comment]
@srhmike any update on this? I've been testing with sandbox transactions and they're coming through just fine.

**Comment by srhmike** [comment]
I found this in my paypal error log
[2017-01-10 04:30:44] Failed to save information in PayPal transactions table. (22001/1406/Data too long for column 'referrer_id' at row 1)
For every time donated.

**Comment by srhmike** [comment]
Not using sandbox
