### ISSUE TITLE
birthdate registration

### ISSUE THREAD

**Issue by daisyanne1380** [rathena/FluxCP#99]
when creating an account it as for your birthdate, currently the lowest birthday year that a member can go is 1987. Is there a way to increase the years on Birthdate drop down

**Comment by Akkarinage** [comment]
Look for 'BackwardYears' in config/application.php

**Comment by daisyanne1380** [comment]
thank you

**Comment by daisyanne1380** [comment]
sorry i posted cause i didn't see my topic i thought i had forgotten to
post it.  so its there again. once again sorry and thank you
